#nullable enable

/* This code was generated by FastCloner.Internalization.Builder, do not edit manually
FastCloner is licensed under the MIT licence. https://github.com/lofcz/FastCloner
*/

using System.Linq.Expressions;
using System.Reflection;
using System;
using System.Collections.Generic;

namespace Foundatio.FastCloner.Code;
internal static class ClonerToExprGenerator
{
    internal static object GenerateClonerInternal(Type realType, bool isDeepClone)
    {
        return realType.IsValueType() ? throw new InvalidOperationException("Operation is valid only for reference types") : GenerateProcessMethod(realType, isDeepClone);
    }

    private static object GenerateProcessMethod(Type type, bool isDeepClone)
    {
        if (type.IsArray)
        {
            return GenerateProcessArrayMethod(type, isDeepClone);
        }

        Type methodType = typeof(object);
        List<Expression> expressionList = [];
        ParameterExpression from = Expression.Parameter(methodType);
        ParameterExpression fromLocal = from;
        ParameterExpression to = Expression.Parameter(methodType);
        ParameterExpression toLocal = to;
        ParameterExpression state = Expression.Parameter(typeof(FastCloneState));
        // if (!type.IsValueType())
        {
            fromLocal = Expression.Variable(type);
            toLocal = Expression.Variable(type);
            // fromLocal = (T)from
            expressionList.Add(Expression.Assign(fromLocal, Expression.Convert(from, type)));
            expressionList.Add(Expression.Assign(toLocal, Expression.Convert(to, type)));
            if (isDeepClone)
            {
                // added from -> to binding to ensure reference loop handling
                // structs cannot loop here
                // state.AddKnownRef(from, to)
                expressionList.Add(Expression.Call(state, StaticMethodInfos.DeepCloneStateMethods.AddKnownRef, from, to));
            }
        }

        foreach (FieldInfo fieldInfo in EnumerateFields(type))
        {
            // Check if member should be shallow cloned (copy reference directly)
            if (FastClonerExprGenerator.MemberIsShallow(fieldInfo))
            {
                Expression sourceValue = Expression.Field(fromLocal, fieldInfo);
                if (fieldInfo.IsInitOnly)
                {
                    ConstantExpression setter = Expression.Constant(FieldAccessorGenerator.GetFieldSetter(fieldInfo));
                    expressionList.Add(Expression.Invoke(setter, Expression.Convert(toLocal, typeof(object)), Expression.Convert(sourceValue, typeof(object))));
                }
                else
                {
                    expressionList.Add(Expression.Assign(Expression.Field(toLocal, fieldInfo), sourceValue));
                }
            }
            else if (isDeepClone && !FastClonerSafeTypes.CanReturnSameObject(fieldInfo.FieldType))
            {
                MethodInfo methodInfo = StaticMethodInfos.DeepClonerGeneratorMethods.MakeFieldCloneMethodInfo(fieldInfo.FieldType);
                MemberExpression get = Expression.Field(fromLocal, fieldInfo);
                // toLocal.Field = Clone...Internal(fromLocal.Field)
                Expression call = Expression.Call(methodInfo, get, state);
                if (!fieldInfo.FieldType.IsValueType())
                    call = Expression.Convert(call, fieldInfo.FieldType);
                if (fieldInfo.IsInitOnly)
                {
                    ConstantExpression setter = Expression.Constant(FieldAccessorGenerator.GetFieldSetter(fieldInfo));
                    expressionList.Add(Expression.Invoke(setter, Expression.Convert(toLocal, typeof(object)), Expression.Convert(call, typeof(object))));
                }
                else
                {
                    expressionList.Add(Expression.Assign(Expression.Field(toLocal, fieldInfo), call));
                }
            }
            else
            {
                Expression sourceValue = Expression.Field(fromLocal, fieldInfo);
                if (fieldInfo.IsInitOnly)
                {
                    ConstantExpression setter = Expression.Constant(FieldAccessorGenerator.GetFieldSetter(fieldInfo));
                    expressionList.Add(Expression.Invoke(setter, Expression.Convert(toLocal, typeof(object)), Expression.Convert(sourceValue, typeof(object))));
                }
                else
                {
                    expressionList.Add(Expression.Assign(Expression.Field(toLocal, fieldInfo), sourceValue));
                }
            }
        }

        expressionList.Add(Expression.Convert(toLocal, methodType));
        Type funcType = typeof(Func<,,, >).MakeGenericType(methodType, methodType, typeof(FastCloneState), methodType);
        List<ParameterExpression> blockParams = [];
        if (from != fromLocal)
            blockParams.Add(fromLocal);
        if (to != toLocal)
            blockParams.Add(toLocal);
        return Expression.Lambda(funcType, Expression.Block(blockParams, expressionList), from, to, state).Compile();
        static IEnumerable<FieldInfo> EnumerateFields(Type sourceType)
        {
            Type? tp = sourceType;
            while (tp != null && tp != typeof(ContextBoundObject))
            {
                foreach (FieldInfo field in tp.GetDeclaredFields())
                {
                    yield return field;
                }

                tp = tp.BaseType();
            }
        }
    }

    private static object GenerateProcessArrayMethod(Type type, bool isDeep)
    {
        Type elementType = type.GetElementType()!;
        int rank = type.GetArrayRank();
        ParameterExpression from = Expression.Parameter(typeof(object));
        ParameterExpression to = Expression.Parameter(typeof(object));
        ParameterExpression state = Expression.Parameter(typeof(FastCloneState));
        Type funcType = typeof(Func<,,, >).MakeGenericType(typeof(object), typeof(object), typeof(FastCloneState), typeof(object));
        if (rank == 1 && type == elementType.MakeArrayType())
        {
            if (!isDeep)
            {
                MethodCallExpression callS = Expression.Call(typeof(ClonerToExprGenerator).GetPrivateStaticMethod(nameof(ShallowClone1DimArraySafeInternal))!.MakeGenericMethod(elementType), Expression.Convert(from, type), Expression.Convert(to, type));
                return Expression.Lambda(funcType, callS, from, to, state).Compile();
            }
            else
            {
                string methodName = nameof(Clone1DimArrayClassInternal);
                if (FastClonerSafeTypes.CanReturnSameObject(elementType))
                    methodName = nameof(Clone1DimArraySafeInternal);
                else if (elementType.IsValueType())
                    methodName = nameof(Clone1DimArrayStructInternal);
                MethodInfo methodInfo = typeof(ClonerToExprGenerator).GetPrivateStaticMethod(methodName)!.MakeGenericMethod(elementType);
                MethodCallExpression callS = Expression.Call(methodInfo, Expression.Convert(from, type), Expression.Convert(to, type), state);
                return Expression.Lambda(funcType, callS, from, to, state).Compile();
            }
        }

        {
            // multidim or not zero-based arrays
            MethodInfo methodInfo;
            if (rank == 2 && type == elementType.MakeArrayType(2))
                methodInfo = typeof(ClonerToExprGenerator).GetPrivateStaticMethod(nameof(Clone2DimArrayInternal))!.MakeGenericMethod(elementType);
            else
                methodInfo = typeof(ClonerToExprGenerator).GetPrivateStaticMethod(nameof(CloneAbstractArrayInternal))!;
            MethodCallExpression callS = Expression.Call(methodInfo, Expression.Convert(from, type), Expression.Convert(to, type), state, Expression.Constant(isDeep));
            return Expression.Lambda(funcType, callS, from, to, state).Compile();
        }
    }

    // when we can't use code generation, we can use these methods
    internal static T[] ShallowClone1DimArraySafeInternal<T>(T[] objFrom, T[] objTo)
    {
        int l = Math.Min(objFrom.Length, objTo.Length);
        Array.Copy(objFrom, objTo, l);
        return objTo;
    }

    // when we can't use code generation, we can use these methods
    internal static T[] Clone1DimArraySafeInternal<T>(T[] objFrom, T[] objTo, FastCloneState state)
    {
        int l = Math.Min(objFrom.Length, objTo.Length);
        state.AddKnownRef(objFrom, objTo);
        Array.Copy(objFrom, objTo, l);
        return objTo;
    }

    internal static T[]? Clone1DimArrayStructInternal<T>(T[]? objFrom, T[]? objTo, FastCloneState state)
    {
        // not null from called method, but will check it anyway
        if (objFrom == null || objTo == null)
            return null;
        int l = Math.Min(objFrom.Length, objTo.Length);
        state.AddKnownRef(objFrom, objTo);
        Func<T, FastCloneState, T>? cloner = FastClonerGenerator.GetClonerForValueType<T>();
        if (cloner is not null)
        {
            for (int i = 0; i < l; i++)
            {
                objTo[i] = cloner(objFrom[i], state);
            }
        }

        return objTo;
    }

    internal static T[]? Clone1DimArrayClassInternal<T>(T[]? objFrom, T[]? objTo, FastCloneState state)
    {
        // not null from called method, but will check it anyway
        if (objFrom == null || objTo == null)
            return null;
        int l = Math.Min(objFrom.Length, objTo.Length);
        state.AddKnownRef(objFrom, objTo);
        for (int i = 0; i < l; i++)
            objTo[i] = (T)FastClonerGenerator.CloneClassInternal(objFrom[i], state)!;
        return objTo;
    }

    internal static T[, ]? Clone2DimArrayInternal<T>(T[, ]? objFrom, T[, ]? objTo, FastCloneState state, bool isDeep)
    {
        // not null from called method, but will check it anyway
        if (objFrom == null || objTo == null)
            return null;
        int fromLower0 = objFrom.GetLowerBound(0);
        int fromLower1 = objFrom.GetLowerBound(1);
        int toLower0 = objTo.GetLowerBound(0);
        int toLower1 = objTo.GetLowerBound(1);
        if (fromLower0 != 0 || fromLower1 != 0 || toLower0 != 0 || toLower1 != 0)
            return (T[, ]? )CloneAbstractArrayInternal(objFrom, objTo, state, isDeep);
        int fromLength0 = objFrom.GetLength(0);
        int fromLength1 = objFrom.GetLength(1);
        int toLength0 = objTo.GetLength(0);
        int toLength1 = objTo.GetLength(1);
        int l1 = Math.Min(fromLength0, toLength0);
        int l2 = Math.Min(fromLength1, toLength1);
        state.AddKnownRef(objFrom, objTo);
        bool isValueType = typeof(T).IsValueType();
        bool canReturnSame = FastClonerSafeTypes.CanReturnSameObject(typeof(T));
        bool canShallowCopyValues = !isDeep || canReturnSame;
        // 2D arrays are row-major - copy row prefix as one contiguous block
        if (canShallowCopyValues && fromLength1 == toLength1)
        {
            Array.Copy(objFrom, objTo, l1 * fromLength1);
            return objTo;
        }

        if (!isDeep)
        {
            for (int i = 0; i < l1; i++)
                for (int k = 0; k < l2; k++)
                    objTo[i, k] = objFrom[i, k];
            return objTo;
        }

        if (isValueType)
        {
            Func<T, FastCloneState, T>? cloner = FastClonerGenerator.GetClonerForValueType<T>();
            if (cloner is not null)
            {
                for (int i = 0; i < l1; i++)
                    for (int k = 0; k < l2; k++)
                        objTo[i, k] = cloner(objFrom[i, k], state);
            }
        }
        else
        {
            for (int i = 0; i < l1; i++)
                for (int k = 0; k < l2; k++)
                    objTo[i, k] = (T)FastClonerGenerator.CloneClassInternal(objFrom[i, k], state)!;
        }

        return objTo;
    }

    // rare cases, very slow cloning. currently it's ok
    internal static Array? CloneAbstractArrayInternal(Array? objFrom, Array? objTo, FastCloneState state, bool isDeep)
    {
        // not null from called method, but will check it anyway
        if (objFrom == null || objTo == null)
            return null;
        int rank = objFrom.Rank;
        int[] lowerBoundsFrom = new int[rank];
        int[] lowerBoundsTo = new int[rank];
        int[] lengths = new int[rank];
        bool hasZeroLength = false;
        for (int i = 0; i < rank; i++)
        {
            int lowerBoundFrom = objFrom.GetLowerBound(i);
            int lowerBoundTo = objTo.GetLowerBound(i);
            int length = Math.Min(objFrom.GetLength(i), objTo.GetLength(i));
            lowerBoundsFrom[i] = lowerBoundFrom;
            lowerBoundsTo[i] = lowerBoundTo;
            lengths[i] = length;
            hasZeroLength |= length == 0;
        }

        state.AddKnownRef(objFrom, objTo);
        // unable to copy any element
        if (hasZeroLength)
            return objTo;
        if (rank == 1)
        {
            int fromLower = lowerBoundsFrom[0];
            int toLower = lowerBoundsTo[0];
            int len = lengths[0];
            if (isDeep)
            {
                for (int i = 0; i < len; i++)
                    objTo.SetValue(FastClonerGenerator.CloneClassInternal(objFrom.GetValue(fromLower + i), state), toLower + i);
            }
            else
            {
                for (int i = 0; i < len; i++)
                    objTo.SetValue(objFrom.GetValue(fromLower + i), toLower + i);
            }

            return objTo;
        }

        if (rank == 2)
        {
            int fromLower0 = lowerBoundsFrom[0];
            int fromLower1 = lowerBoundsFrom[1];
            int toLower0 = lowerBoundsTo[0];
            int toLower1 = lowerBoundsTo[1];
            int len0 = lengths[0];
            int len1 = lengths[1];
            if (isDeep)
            {
                for (int i = 0; i < len0; i++)
                {
                    int fromI = fromLower0 + i;
                    int toI = toLower0 + i;
                    for (int k = 0; k < len1; k++)
                    {
                        objTo.SetValue(FastClonerGenerator.CloneClassInternal(objFrom.GetValue(fromI, fromLower1 + k), state), toI, toLower1 + k);
                    }
                }
            }
            else
            {
                for (int i = 0; i < len0; i++)
                {
                    int fromI = fromLower0 + i;
                    int toI = toLower0 + i;
                    for (int k = 0; k < len1; k++)
                    {
                        objTo.SetValue(objFrom.GetValue(fromI, fromLower1 + k), toI, toLower1 + k);
                    }
                }
            }

            return objTo;
        }

        int[] idxesFrom = new int[rank];
        int[] idxesTo = new int[rank];
        Array.Copy(lowerBoundsFrom, idxesFrom, rank);
        Array.Copy(lowerBoundsTo, idxesTo, rank);
        if (isDeep)
        {
            while (true)
            {
                objTo.SetValue(FastClonerGenerator.CloneClassInternal(objFrom.GetValue(idxesFrom), state), idxesTo);
                int ofs = rank - 1;
                while (true)
                {
                    idxesFrom[ofs]++;
                    idxesTo[ofs]++;
                    if (idxesFrom[ofs] >= lowerBoundsFrom[ofs] + lengths[ofs])
                    {
                        idxesFrom[ofs] = lowerBoundsFrom[ofs];
                        idxesTo[ofs] = lowerBoundsTo[ofs];
                        ofs--;
                        if (ofs < 0)
                            return objTo;
                    }
                    else
                        break;
                }
            }
        }
        else
        {
            while (true)
            {
                objTo.SetValue(objFrom.GetValue(idxesFrom), idxesTo);
                int ofs = rank - 1;
                while (true)
                {
                    idxesFrom[ofs]++;
                    idxesTo[ofs]++;
                    if (idxesFrom[ofs] >= lowerBoundsFrom[ofs] + lengths[ofs])
                    {
                        idxesFrom[ofs] = lowerBoundsFrom[ofs];
                        idxesTo[ofs] = lowerBoundsTo[ofs];
                        ofs--;
                        if (ofs < 0)
                            return objTo;
                    }
                    else
                        break;
                }
            }
        }
    }
}
