#nullable enable

/* This code was generated by FastCloner.Internalization.Builder, do not edit manually
FastCloner is licensed under the MIT licence. https://github.com/lofcz/FastCloner
*/

using System.Collections.ObjectModel;
using System;
using System.Collections.Generic;

namespace Foundatio.FastCloner.Code;
internal sealed class FastClonerRuntimeConfig
{
    private static readonly ReadOnlyDictionary<Type, CloneBehavior> emptyTypeBehaviors = new ReadOnlyDictionary<Type, CloneBehavior>(new Dictionary<Type, CloneBehavior>());
    internal static readonly FastClonerRuntimeConfig Default = new FastClonerRuntimeConfig(maxRecursionDepth: 1_000, disableOptionalFeatures: false, typeBehaviors: emptyTypeBehaviors, cacheKey: 0);
    private FastClonerRuntimeConfig(int maxRecursionDepth, bool disableOptionalFeatures, ReadOnlyDictionary<Type, CloneBehavior> typeBehaviors, long cacheKey)
    {
        MaxRecursionDepth = maxRecursionDepth;
        DisableOptionalFeatures = disableOptionalFeatures;
        TypeBehaviors = typeBehaviors;
        CacheKey = cacheKey;
        HasTypeBehaviorOverrides = typeBehaviors.Count > 0;
        HasActiveTypeBehaviorOverrides = HasTypeBehaviorOverrides && !disableOptionalFeatures;
        HasSafeTypeOverrides = HasActiveTypeBehaviorOverrides && CalculateHasSafeTypeOverrides(typeBehaviors);
    }

    public int MaxRecursionDepth { get; }
    public bool DisableOptionalFeatures { get; }
    public ReadOnlyDictionary<Type, CloneBehavior> TypeBehaviors { get; }
    public long CacheKey { get; }
    public bool HasTypeBehaviorOverrides { get; }
    public bool HasActiveTypeBehaviorOverrides { get; }
    public bool HasSafeTypeOverrides { get; }

    public static FastClonerRuntimeConfig Create(int maxRecursionDepth, bool disableOptionalFeatures, Dictionary<Type, CloneBehavior>? typeBehaviors, long cacheKey, bool useStartupDefaultSingleton = true)
    {
        if (maxRecursionDepth == Default.MaxRecursionDepth && !disableOptionalFeatures && (typeBehaviors is null || typeBehaviors.Count == 0) && useStartupDefaultSingleton)
        {
            return Default;
        }

        ReadOnlyDictionary<Type, CloneBehavior> behaviors = typeBehaviors is { Count: > 0 } ? new ReadOnlyDictionary<Type, CloneBehavior>(new Dictionary<Type, CloneBehavior>(typeBehaviors)) : emptyTypeBehaviors;
        return new FastClonerRuntimeConfig(maxRecursionDepth, disableOptionalFeatures, behaviors, cacheKey);
    }

    public Dictionary<Type, CloneBehavior> CloneTypeBehaviors()
    {
        return TypeBehaviors.Count == 0 ? new Dictionary<Type, CloneBehavior>() : new Dictionary<Type, CloneBehavior>(TypeBehaviors);
    }

    public CloneBehavior? GetTypeBehavior(Type type)
    {
        return TypeBehaviors.TryGetValue(type, out CloneBehavior behavior) ? behavior : null;
    }

    public bool IsTypeIgnored(Type type)
    {
        return HasActiveTypeBehaviorOverrides && TypeBehaviors.TryGetValue(type, out CloneBehavior behavior) && behavior == CloneBehavior.Ignore;
    }

    public bool IsTypeReference(Type type)
    {
        return HasActiveTypeBehaviorOverrides && TypeBehaviors.TryGetValue(type, out CloneBehavior behavior) && behavior == CloneBehavior.Reference;
    }

    private static bool CalculateHasSafeTypeOverrides(IReadOnlyDictionary<Type, CloneBehavior> typeBehaviors)
    {
        foreach (KeyValuePair<Type, CloneBehavior> kvp in typeBehaviors)
        {
            if (kvp.Value == CloneBehavior.Ignore && FastClonerSafeTypes.DefaultKnownTypes.ContainsKey(kvp.Key))
                return true;
        }

        return false;
    }
}

internal sealed class FastClonerPublishedEngine
{
    private FastClonerPublishedEngine(FastClonerRuntimeConfig runtimeConfig, bool usesStartupDefaultRail)
    {
        RuntimeConfig = runtimeConfig;
        UsesStartupDefaultRail = usesStartupDefaultRail;
    }

    internal static FastClonerPublishedEngine StartupDefault { get; } = new FastClonerPublishedEngine(FastClonerRuntimeConfig.Default, usesStartupDefaultRail: true);
    public FastClonerRuntimeConfig RuntimeConfig { get; }
    public bool UsesStartupDefaultRail { get; }
    public long CacheKey => RuntimeConfig.CacheKey;

    public static FastClonerPublishedEngine CreateConfigured(FastClonerRuntimeConfig runtimeConfig)
    {
        return new FastClonerPublishedEngine(runtimeConfig, usesStartupDefaultRail: false);
    }
}

internal static class FastClonerRuntimeConfigScope
{
    [ThreadStatic]
    private static FastClonerRuntimeConfig? current;
    public static FastClonerRuntimeConfig? TryGetCurrent() => current;
    public static FastClonerRuntimeConfig Current => current ?? FastCloner.GetRuntimeConfigSnapshot();

    public static Scope Use(FastClonerRuntimeConfig config)
    {
        return new Scope(config);
    }

    internal readonly struct Scope : IDisposable
    {
        private readonly FastClonerRuntimeConfig? previous;
        public Scope(FastClonerRuntimeConfig config)
        {
            previous = current;
            current = config;
        }

        public void Dispose()
        {
            current = previous;
        }
    }
}
