#nullable enable annotations
#nullable disable warnings

/* This code was generated by FastCloner.Internalization.Builder, do not edit manually
FastCloner is licensed under the MIT licence. https://github.com/lofcz/FastCloner
*/

using System.Runtime.CompilerServices;
using System;

namespace Foundatio.FastCloner.Code;
internal sealed class FastCloneState
{
    private const int InlineKnownRefCapacity = 4;
    private const int MetadataCacheSize = 4;
    private const int InitialWorkQueueCapacity = 16;
    private const int MaxRetainedWorkQueueCapacity = 4096;
    private const int MaxPoolSize = 16;
    [ThreadStatic]
    private static FastCloneState? []? _pool;
    [ThreadStatic]
    private static int _poolCount;
    [ThreadStatic]
    private static FastCloneState? _simpleState;
    public bool TrackReferences { get; }
    public int MaxRecursionDepth { get; private set; } = FastCloner.MaxRecursionDepth;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static FastCloneState GetSimpleState()
    {
        FastCloneState state = _simpleState ?? CreateSimpleState();
        if (state.MaxRecursionDepth != FastCloner.MaxRecursionDepth)
            state.MaxRecursionDepth = FastCloner.MaxRecursionDepth;
        return state;
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static FastCloneState CreateSimpleState()
    {
        FastCloneState state = new FastCloneState(trackReferences: false);
        _simpleState = state;
        return state;
    }

    public static FastCloneState Rent()
    {
        FastCloneState? []? pool = _pool;
        if (pool != null && _poolCount > 0)
        {
            int index = --_poolCount;
            FastCloneState? state = pool[index];
            pool[index] = null;
            if (state != null)
            {
                if (state.MaxRecursionDepth != FastCloner.MaxRecursionDepth)
                    state.MaxRecursionDepth = FastCloner.MaxRecursionDepth;
                return state;
            }
        }

        return new FastCloneState
        {
            MaxRecursionDepth = FastCloner.MaxRecursionDepth
        };
    }

    public static void Return(FastCloneState state)
    {
        state.Reset();
        FastCloneState? [] pool = _pool ??= new FastCloneState[MaxPoolSize];
        if (_poolCount < MaxPoolSize)
        {
            pool[_poolCount++] = state;
        }
    }

    private void Reset()
    {
        for (int i = 0; i < idx; i++)
        {
            baseFromTo[i] = null !;
            baseFromTo[i + InlineKnownRefCapacity] = null !;
        }

        idx = 0;
        if (loops is { } localLoops)
        {
            if (localLoops.Capacity > 4096)
                loops = null;
            else
                localLoops.Clear();
        }

        if (workItems is { } localWorkItems)
        {
            if (workCount > 0)
                Array.Clear(localWorkItems, 0, workCount);
            if (localWorkItems.Length > MaxRetainedWorkQueueCapacity)
                workItems = null;
        }

        workCount = 0;
        UseWorkList = false;
        callDepth = 0;
        metadataTypes[0] = null;
        metadataTypes[1] = null;
        metadataTypes[2] = null;
        metadataTypes[3] = null;
        metadataWriteIndex = 0;
    }

    private FastCloneState(bool trackReferences = true)
    {
        TrackReferences = trackReferences;
    }

    private MiniDictionary? loops;
    private readonly object[] baseFromTo = new object[InlineKnownRefCapacity * 2];
    private int idx;
    private WorkItem[]? workItems;
    private int workCount;
    public bool UseWorkList { get; set; }

    private int callDepth;
    internal int CurrentDepth => callDepth;

    private readonly Type? [] metadataTypes = new Type? [MetadataCacheSize];
    private readonly FastClonerCache.TypeCloneMetadata[] metadataValues = new FastClonerCache.TypeCloneMetadata[MetadataCacheSize];
    private int metadataWriteIndex;
    private readonly struct WorkItem(object from, object to, Type type)
    {
        public readonly object From = from;
        public readonly object To = to;
        public readonly Type Type = type;
    }

    public object? GetKnownRef(object from)
    {
        if (!TrackReferences)
            return null;
        if (idx > 0 && ReferenceEquals(from, baseFromTo[0]))
            return baseFromTo[InlineKnownRefCapacity];
        if (idx > 1 && ReferenceEquals(from, baseFromTo[1]))
            return baseFromTo[InlineKnownRefCapacity + 1];
        if (idx > 2 && ReferenceEquals(from, baseFromTo[2]))
            return baseFromTo[InlineKnownRefCapacity + 2];
        if (idx > 3 && ReferenceEquals(from, baseFromTo[3]))
            return baseFromTo[InlineKnownRefCapacity + 3];
        return loops?.FindEntry(from);
    }

    public void AddKnownRef(object from, object to)
    {
        if (!TrackReferences)
            return;
        if (idx < InlineKnownRefCapacity)
        {
            baseFromTo[idx] = from;
            baseFromTo[idx + InlineKnownRefCapacity] = to;
            idx++;
            return;
        }

        loops ??= new MiniDictionary();
        loops.Insert(from, to);
    }

    public void EnsureKnownRefCapacity(int totalExpectedReferences)
    {
        if (!TrackReferences || totalExpectedReferences <= InlineKnownRefCapacity)
            return;
        int expectedInDictionary = totalExpectedReferences - InlineKnownRefCapacity;
        if (expectedInDictionary <= 0)
            return;
        if (loops is null)
        {
            loops = new MiniDictionary(expectedInDictionary);
            return;
        }

        loops.EnsureCapacity(expectedInDictionary);
    }

    public void EnqueueProcess(object from, object to, Type type)
    {
        if (!TrackReferences)
            return;
        WorkItem[] local = workItems ??= new WorkItem[InitialWorkQueueCapacity];
        if (workCount == local.Length)
        {
            int newSize = GetExpandedCapacity(local.Length, workCount + 1);
            WorkItem[] resized = new WorkItem[newSize];
            Array.Copy(local, resized, workCount);
            workItems = local = resized;
        }

        local[workCount++] = new WorkItem(from, to, type);
    }

    public void EnsureWorkQueueCapacity(int expectedAdditionalItems)
    {
        if (!TrackReferences || expectedAdditionalItems <= 0)
            return;
        int needed = checked(workCount + expectedAdditionalItems);
        WorkItem[] local = workItems ??= new WorkItem[Math.Max(InitialWorkQueueCapacity, expectedAdditionalItems)];
        if (needed <= local.Length)
            return;
        int newSize = GetExpandedCapacity(local.Length, needed);
        WorkItem[] resized = new WorkItem[newSize];
        Array.Copy(local, resized, workCount);
        workItems = resized;
    }

    public bool TryPop(out object from, out object to, out Type type)
    {
        if (!TrackReferences)
        {
            from = null !;
            to = null !;
            type = null !;
            return false;
        }

        if (workCount == 0)
        {
            from = null !;
            to = null !;
            type = null !;
            return false;
        }

        int index = --workCount;
        WorkItem wi = workItems![index];
        workItems[index] = default;
        from = wi.From;
        to = wi.To;
        type = wi.Type;
        return true;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static int GetExpandedCapacity(int currentCapacity, int minimumRequiredCapacity)
    {
        int newSize = currentCapacity;
        while (newSize < minimumRequiredCapacity)
        {
            if (newSize > int.MaxValue / 2)
                return minimumRequiredCapacity;
            newSize *= 2;
        }

        return newSize;
    }

    public int IncrementDepth() => ++callDepth;
    public void DecrementDepth()
    {
        if (callDepth > 0)
            callDepth--;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool TryGetCachedTypeMetadata(Type type, out FastClonerCache.TypeCloneMetadata metadata)
    {
        if (ReferenceEquals(type, metadataTypes[0]))
        {
            metadata = metadataValues[0];
            return true;
        }

        if (ReferenceEquals(type, metadataTypes[1]))
        {
            metadata = metadataValues[1];
            return true;
        }

        if (ReferenceEquals(type, metadataTypes[2]))
        {
            metadata = metadataValues[2];
            return true;
        }

        if (ReferenceEquals(type, metadataTypes[3]))
        {
            metadata = metadataValues[3];
            return true;
        }

        metadata = null !;
        return false;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void CacheTypeMetadata(Type type, FastClonerCache.TypeCloneMetadata metadata)
    {
        if (ReferenceEquals(type, metadataTypes[0]))
        {
            metadataValues[0] = metadata;
            return;
        }

        if (ReferenceEquals(type, metadataTypes[1]))
        {
            metadataValues[1] = metadata;
            return;
        }

        if (ReferenceEquals(type, metadataTypes[2]))
        {
            metadataValues[2] = metadata;
            return;
        }

        if (ReferenceEquals(type, metadataTypes[3]))
        {
            metadataValues[3] = metadata;
            return;
        }

        int index = metadataWriteIndex;
        metadataTypes[index] = type;
        metadataValues[index] = metadata;
        metadataWriteIndex = (index + 1) & (MetadataCacheSize - 1);
    }

    private sealed class MiniDictionary
    {
        private struct Entry(int hashCode, int next, object key, object value)
        {
            public readonly int HashCode = hashCode;
            public int Next = next;
            public readonly object Key = key;
            public readonly object Value = value;
        }

        private const int DefaultCapacity = 8;
        private int[] buckets;
        private Entry[] entries;
        private int count;
        private int bucketMask;
        public int Capacity => entries.Length;

        public MiniDictionary() : this(DefaultCapacity)
        {
        }

        public MiniDictionary(int capacity)
        {
            int size = RoundUpToPowerOf2(capacity < DefaultCapacity ? DefaultCapacity : capacity);
            Initialize(size);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static int RoundUpToPowerOf2(int value)
        {
            --value;
            value |= value >> 1;
            value |= value >> 2;
            value |= value >> 4;
            value |= value >> 8;
            value |= value >> 16;
            return value + 1;
        }

        public object? FindEntry(object key)
        {
            int hashCode = RuntimeHelpers.GetHashCode(key) & 0x7FFFFFFF;
            int bucketIndex = hashCode & bucketMask;
            Entry[] entriesLocal = entries;
            for (int i = buckets[bucketIndex]; i >= 0; i = entriesLocal[i].Next)
            {
                ref readonly Entry entry = ref entriesLocal[i];
                if (entry.HashCode == hashCode && ReferenceEquals(entry.Key, key))
                    return entry.Value;
            }

            return null;
        }

        private void Initialize(int size)
        {
            buckets = new int[size];
            Array.Fill(buckets, -1);
            entries = new Entry[size];
            bucketMask = size - 1;
        }

        public void Clear()
        {
            if (count == 0)
                return;
            Array.Clear(entries, 0, count);
            Array.Fill(buckets, -1);
            count = 0;
        }

        public void EnsureCapacity(int capacity)
        {
            if (capacity <= entries.Length)
                return;
            Resize(RoundUpToPowerOf2(capacity));
        }

        public void Insert(object key, object value)
        {
            int hashCode = RuntimeHelpers.GetHashCode(key) & 0x7FFFFFFF;
            int[] localBuckets = buckets;
            Entry[] localEntries = entries;
            if (count == localEntries.Length)
            {
                Resize();
                localBuckets = buckets;
                localEntries = entries;
            }

            int targetBucket = hashCode & bucketMask;
            int index = count++;
            localEntries[index] = new Entry(hashCode, localBuckets[targetBucket], key, value);
            localBuckets[targetBucket] = index;
        }

        private void Resize() => Resize(entries.Length * 2);
        private void Resize(int newSize)
        {
            int[] newBuckets = new int[newSize];
            Array.Fill(newBuckets, -1);
            Entry[] newEntries = new Entry[newSize];
            Array.Copy(entries, newEntries, count);
            int newMask = newSize - 1;
            for (int i = 0; i < count; i++)
            {
                ref Entry entry = ref newEntries[i];
                int bucket = entry.HashCode & newMask;
                entry.Next = newBuckets[bucket];
                newBuckets[bucket] = i;
            }

            buckets = newBuckets;
            entries = newEntries;
            bucketMask = newMask;
        }
    }
}
