#nullable enable

/* This code was generated by FastCloner.Internalization.Builder, do not edit manually
FastCloner is licensed under the MIT licence. https://github.com/lofcz/FastCloner
*/

using System;

namespace Foundatio.FastCloner.Code;
/// <summary>
/// Specifies the cloning behavior for a member (field, property, event) or an entire type (class, struct, record).
/// When applied to a type, all members of that type will use this behavior unless overridden at the member level.
/// This is the base attribute for configuring clone behavior.
/// </summary>
/// <example>
/// <code>
/// // Type-level: all usages of SharedService will preserve reference
/// [FastClonerBehavior(CloneBehavior.Reference)]
/// public class SharedService { }
/// 
/// // Member-level: override behavior for specific members
/// public class MyClass
/// {
///     [FastClonerBehavior(CloneBehavior.Ignore)]
///     public CancellationToken Token { get; set; }  // Set to default
/// }
/// </code>
/// </example>
[AttributeUsage(AttributeTargets.Field | AttributeTargets.Property | AttributeTargets.Event | AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Interface)]
internal class FastClonerBehaviorAttribute(CloneBehavior behavior) : Attribute
{
    /// <summary>
    /// Gets the cloning behavior.
    /// </summary>
    public CloneBehavior Behavior { get; } = behavior;
}
