/* This code was generated by FastCloner.Internalization.Builder, do not edit manually
FastCloner is licensed under the MIT licence. https://github.com/lofcz/FastCloner
*/

using System.Collections.Concurrent;
using System.Reflection;
using System.Runtime.CompilerServices;
using System;
using System.Collections.Generic;
using System.Threading;

namespace Foundatio.FastCloner.Code;
/// <summary>
/// Specifies how a type should be handled during cloning.
/// </summary>
internal enum CloneBehavior
{
    /// <summary>
    /// Perform deep cloning (default behavior).
    /// </summary>
    Clone,
    /// <summary>
    /// Return the same instance without cloning (for immutable/safe types).
    /// </summary>
    Reference,
    /// <summary>
    /// Perform shallow cloning (MemberwiseClone).
    /// </summary>
    Shallow,
    /// <summary>
    /// Skip cloning, return default.
    /// </summary>
    Ignore
}

/// <summary>
/// Generic static cache that leverages JIT specialization to avoid dictionary lookups
/// when the compile-time type T matches the runtime type.
/// </summary>
internal static class ClonerCache<T>
{
    internal readonly struct CacheEntry(Func<T, FastCloneState, T>? cloner, bool isSafe, bool canUseNoTrackingState, FastClonerCache.TypeCloneMetadata? metadata)
    {
        public Func<T, FastCloneState, T>? Cloner { get; } = cloner;
        public bool IsSafe { get; } = isSafe;
        public bool CanUseNoTrackingState { get; } = canUseNoTrackingState;
        public FastClonerCache.TypeCloneMetadata? Metadata { get; } = metadata;
    }

#if NET10_0_OR_GREATER
    private static readonly System.Threading.Lock sync = new System.Threading.Lock();
#else
    private static readonly object sync = new object();
#endif
    private static Func<T, FastCloneState, T>? cloner;
    private static bool isSafe;
    private static bool canUseNoTrackingState;
    private static FastClonerCache.TypeCloneMetadata? metadata;
    private static long version = -1;
    public static CacheEntry GetCurrent()
    {
        long currentVersion = FastClonerCache.GetCacheVersion();
        if (Volatile.Read(ref version) != currentVersion)
        {
            lock (sync)
            {
                if (version != currentVersion)
                {
                    Refresh(currentVersion);
                }
            }
        }

        return new CacheEntry(cloner, isSafe, canUseNoTrackingState, metadata);
    }

    private static void Refresh(long currentVersion)
    {
        Type type = typeof(T);
        FastClonerCache.TypeCloneMetadata typeMetadata = FastClonerGenerator.GetTypeMetadata(type);
        bool computedIsSafe = FastClonerSafeTypes.CanReturnSameObject(type);
        bool computedCanUseNoTrackingState = !type.IsValueType && typeMetadata is { CyclePolicy: FastClonerCache.CyclePolicy.None, HasBehaviorSensitiveMembers: false } && !FastClonerCache.HasActiveTypeBehaviorOverrides;
        Func<T, FastCloneState, T>? computedCloner = null;
        if (!computedIsSafe)
        {
            object? clonerObj = FastClonerExprGenerator.GenerateClonerInternal(type, type.IsValueType);
            if (type.IsValueType)
            {
                computedCloner = clonerObj as Func<T, FastCloneState, T>;
            }
            else
            {
                if (clonerObj is Func<object, FastCloneState, object> objectCloner)
                {
                    computedCloner = (obj, state) => (T)objectCloner(obj!, state);
                }
            }
        }

        cloner = computedCloner;
        isSafe = computedIsSafe;
        canUseNoTrackingState = computedCanUseNoTrackingState;
        metadata = typeMetadata;
        Volatile.Write(ref version, currentVersion);
    }
}

internal static class FastClonerCache
{
    private static long cacheVersion = 1;
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static long GetCacheVersion() => Interlocked.Read(ref cacheVersion);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static long BumpCacheVersion() => Interlocked.Increment(ref cacheVersion);
    internal enum CyclePolicy
    {
        None = 0,
        TrackReferences = 1,
        Worklist = 2
    }

    internal sealed class TypeCloneMetadata
    {
        public bool IsSafe { get; set; }
        public bool CanSkipReferenceTracking { get; set; }
        public bool HasBehaviorSensitiveMembers { get; set; }
        public bool RequiresSpecializedCloner { get; set; }
        public CyclePolicy CyclePolicy { get; set; }
        public Func<object, FastCloneState, object>? RecursiveCloner { get; set; }
    }

    internal sealed class TypeShape
    {
        public MemberInfo[] Members { get; init; } = [];
        public Dictionary<string, Type>? IgnoredEventDetails { get; init; }
        public Type[] CycleFieldTypes { get; init; } = [];
        public bool HasReadonlyFields { get; init; }
        public bool ContainsIgnoredMembers { get; init; }
        public bool HasDirectSelfReference { get; init; }
    }

    internal static readonly ConcurrentDictionary<Type, CloneBehavior> TypeBehaviors = [];
    internal static volatile bool HasTypeBehaviorOverrides;
    internal static volatile bool HasActiveTypeBehaviorOverrides;
    internal static bool IsTypeIgnored(Type type)
    {
        return HasActiveTypeBehaviorOverrides && TypeBehaviors.TryGetValue(type, out CloneBehavior behavior) && behavior == CloneBehavior.Ignore;
    }

    internal static volatile bool HasSafeTypeOverrides;
    internal static bool IsTypeReference(Type type)
    {
        return HasActiveTypeBehaviorOverrides && TypeBehaviors.TryGetValue(type, out CloneBehavior behavior) && behavior == CloneBehavior.Reference;
    }

    internal static CloneBehavior? GetTypeBehavior(Type type)
    {
        return TypeBehaviors.TryGetValue(type, out CloneBehavior behavior) ? behavior : null;
    }

    internal static void RecalculateTypeBehaviorState()
    {
        HasTypeBehaviorOverrides = !TypeBehaviors.IsEmpty;
        HasActiveTypeBehaviorOverrides = HasTypeBehaviorOverrides && !FastCloner.DisableOptionalFeatures;
        HasSafeTypeOverrides = CalculateHasSafeTypeOverrides();
    }

    private static bool CalculateHasSafeTypeOverrides()
    {
        if (!HasTypeBehaviorOverrides)
            return false;
        foreach (KeyValuePair<Type, CloneBehavior> kvp in TypeBehaviors)
        {
            if (kvp.Value == CloneBehavior.Ignore && FastClonerSafeTypes.DefaultKnownTypes.ContainsKey(kvp.Key))
                return true;
        }

        return false;
    }

    private sealed class CacheStore
    {
        public readonly ClrCache<object?> ClassCache = new ClrCache<object?>();
        public readonly ClrCache<TypeCloneMetadata> TypeMetadataCache = new ClrCache<TypeCloneMetadata>();
        public readonly ClrCache<TypeShape> TypeShapeCache = new ClrCache<TypeShape>();
        public readonly ClrCache<object?> StructCache = new ClrCache<object?>();
        public readonly ClrCache<object> DeepClassToCache = new ClrCache<object>();
        public readonly ClrCache<object> ShallowClassToCache = new ClrCache<object>();
        public readonly ConcurrentLazyCache<object> TypeConvertCache = new ConcurrentLazyCache<object>();
        public readonly GenericClrCache<TypeNameKey, object?> FieldCache = new GenericClrCache<TypeNameKey, object?>();
        public readonly GenericClrCache<MemberInfo, CloneBehavior?> MemberBehaviorCache = new GenericClrCache<MemberInfo, CloneBehavior?>();
        public readonly ClrCache<CloneBehavior?> AttributedTypeBehaviorCache = new ClrCache<CloneBehavior?>();
        public readonly ClrCache<bool> ImmutableCollectionStatusCache = new ClrCache<bool>();
        public readonly ClrCache<object> SpecialTypesCache = new ClrCache<object>();
        public readonly ClrCache<bool> IsTypeSafeHandleCache = new ClrCache<bool>();
        public readonly ClrCache<bool> AnonymousTypeStatusCache = new ClrCache<bool>();
        public readonly ClrCache<bool> StableHashSemanticsCache = new ClrCache<bool>();
        public readonly ClrCache<bool> CanHaveCyclesCache = new ClrCache<bool>();
        public readonly ClrCache<bool> ValueTypeContainsReferencesCache = new ClrCache<bool>();
        public readonly ClrCache<Type?> CollectionPayloadTypeCache = new ClrCache<Type?>();
        public readonly ClrCache<bool> CompilerGeneratedTypeCache = new ClrCache<bool>();
    }

    private static CacheStore cacheStore = new CacheStore();
    public static object? GetOrAddField(Type type, string name, Func<Type, object?> valueFactory) => cacheStore.FieldCache.GetOrAdd(new TypeNameKey(type, name), k => valueFactory(k.Type));
    public static object? GetOrAddClass(Type type, Func<Type, object?> valueFactory) => cacheStore.ClassCache.GetOrAdd(type, valueFactory);
    public static TypeCloneMetadata GetOrAddTypeMetadata(Type type, Func<Type, TypeCloneMetadata> valueFactory) => cacheStore.TypeMetadataCache.GetOrAdd(type, valueFactory);
    public static TypeShape GetOrAddTypeShape(Type type, Func<Type, TypeShape> valueFactory) => cacheStore.TypeShapeCache.GetOrAdd(type, valueFactory);
    public static object? GetOrAddStructAsObject(Type type, Func<Type, object?> valueFactory) => cacheStore.StructCache.GetOrAdd(type, valueFactory);
    public static object GetOrAddDeepClassTo(Type type, Func<Type, object> valueFactory) => cacheStore.DeepClassToCache.GetOrAdd(type, valueFactory);
    public static object GetOrAddShallowClassTo(Type type, Func<Type, object> valueFactory) => cacheStore.ShallowClassToCache.GetOrAdd(type, valueFactory);
    public static T GetOrAddConvertor<T>(Type from, Type to, Func<Type, Type, T> valueFactory) => (T)cacheStore.TypeConvertCache.GetOrAdd(from, to, (f, t) => valueFactory(f, t));
    public static CloneBehavior? GetOrAddMemberBehavior(MemberInfo memberInfo, Func<MemberInfo, CloneBehavior?> valueFactory) => cacheStore.MemberBehaviorCache.GetOrAdd(memberInfo, valueFactory);
    public static CloneBehavior? GetOrAddAttributedTypeBehavior(Type type, Func<Type, CloneBehavior?> valueFactory) => cacheStore.AttributedTypeBehaviorCache.GetOrAdd(type, valueFactory);
    public static bool GetOrAddImmutableCollectionStatus(Type type, Func<Type, bool> valueFactory) => cacheStore.ImmutableCollectionStatusCache.GetOrAdd(type, valueFactory);
    public static object GetOrAddSpecialType(Type type, Func<Type, object> valueFactory) => cacheStore.SpecialTypesCache.GetOrAdd(type, valueFactory);
    public static bool GetOrAddIsTypeSafeHandle(Type type, Func<Type, bool> valueFactory) => cacheStore.IsTypeSafeHandleCache.GetOrAdd(type, valueFactory);
    public static bool GetOrAddAnonymousTypeStatus(Type type, Func<Type, bool> valueFactory) => cacheStore.AnonymousTypeStatusCache.GetOrAdd(type, valueFactory);
    public static bool GetOrAddStableHashSemantics(Type type, Func<Type, bool> valueFactory) => cacheStore.StableHashSemanticsCache.GetOrAdd(type, valueFactory);
    public static bool GetOrAddCanHaveCycles(Type type, Func<Type, bool> valueFactory) => cacheStore.CanHaveCyclesCache.GetOrAdd(type, valueFactory);
    public static bool GetOrAddValueTypeContainsReferences(Type type, Func<Type, bool> valueFactory) => cacheStore.ValueTypeContainsReferencesCache.GetOrAdd(type, valueFactory);
    public static Type? GetOrAddCollectionPayloadType(Type type, Func<Type, Type?> valueFactory) => cacheStore.CollectionPayloadTypeCache.GetOrAdd(type, valueFactory);
    public static bool GetOrAddCompilerGeneratedType(Type type, Func<Type, bool> valueFactory) => cacheStore.CompilerGeneratedTypeCache.GetOrAdd(type, valueFactory);
    /// <summary>
    /// Clears the FastCloner cached reflection metadata.
    /// </summary>
    public static void ClearCache()
    {
        Volatile.Write(ref cacheStore, new CacheStore());
        FastClonerSafeTypes.ClearKnownTypesCache();
        FastClonerExprGenerator.ClearAdaptiveDictionaryFactoryCache();
        BumpCacheVersion();
    }

    private sealed class ClrCache<TValue>
    {
        private readonly ConcurrentDictionary<IntPtr, TValue> cache = new ConcurrentDictionary<IntPtr, TValue>();
        public TValue GetOrAdd(Type type, Func<Type, TValue> valueFactory)
        {
            IntPtr handle = type.TypeHandle.Value;
            return cache.TryGetValue(handle, out TValue? existing) ? existing : cache.GetOrAdd(handle, _ => valueFactory(type));
        }

        public void Clear() => cache.Clear();
    }

    private sealed class GenericClrCache<TKey, TValue>
        where TKey : notnull
    {
        private readonly ConcurrentDictionary<TKey, TValue> cache = new ConcurrentDictionary<TKey, TValue>();
        public TValue GetOrAdd(TKey key, Func<TKey, TValue> valueFactory)
        {
            return cache.GetOrAdd(key, valueFactory);
        }

        public void Clear() => cache.Clear();
    }

    private readonly struct TypeNameKey(Type type, string name) : IEquatable<TypeNameKey>
    {
        public Type Type { get; } = type;
        public string Name { get; } = name;

        public bool Equals(TypeNameKey other)
        {
            return ReferenceEquals(Type, other.Type) && Name == other.Name;
        }

        public override bool Equals(object? obj)
        {
            return obj is TypeNameKey other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                return (RuntimeHelpers.GetHashCode(Type) * 397) ^ Name.GetHashCode();
            }
        }
    }

    private sealed class ConcurrentLazyCache<TValue>
    {
#if true
        private readonly ConcurrentDictionary<(IntPtr, IntPtr), TValue> cache = new ConcurrentDictionary<(IntPtr, IntPtr), TValue>();
        public TValue GetOrAdd(Type from, Type to, Func<Type, Type, TValue> valueFactory)
        {
            (IntPtr, IntPtr) key = (from.TypeHandle.Value, to.TypeHandle.Value);
            return cache.GetOrAdd(key, _ => valueFactory(from, to));
        }

        public void Clear() => cache.Clear();
#else
        private readonly ConcurrentDictionary<Tuple<IntPtr, IntPtr>, TValue> cache = new ConcurrentDictionary<Tuple<IntPtr, IntPtr>, TValue>();
        
        public TValue GetOrAdd(Type from, Type to, Func<Type, Type, TValue> valueFactory)
        {
            Tuple<IntPtr, IntPtr> key = Tuple.Create(from.TypeHandle.Value, to.TypeHandle.Value);
            return cache.TryGetValue(key, out TValue? cached) ? cached : cache.GetOrAdd(key, _ => valueFactory(from, to));
        }

        public void Clear() => cache.Clear();
#endif
    }
}
