#nullable enable

/* This code was generated by FastCloner.Internalization.Builder, do not edit manually
FastCloner is licensed under the MIT licence. https://github.com/lofcz/FastCloner
*/

using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System;
using System.Collections.Generic;

namespace Foundatio.FastCloner.Code;
internal static class BlittableHelper<T>
{
    public static readonly bool IsBlittable;
    public static readonly int Size;
    static BlittableHelper()
    {
        Type type = typeof(T);
        if (type.IsPrimitive && type != typeof(bool) && type != typeof(char))
        {
            IsBlittable = true;
            Size = Marshal.SizeOf(type);
            return;
        }

        IsBlittable = false;
        Size = 0;
    }
}

internal static class FastArrayCopy<T>
{
    private static readonly Func<T[], T[]> CloneArray = CreateCloneArray();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T[] Clone(T[] source) => CloneArray(source);
    private static Func<T[], T[]> CreateCloneArray()
    {
        if (BlittableHelper<T>.IsBlittable)
            return CloneWithBlockCopy;
        return CloneManaged;
    }

    private static T[] CloneManaged(T[] source) => (T[])source.Clone();
    private static T[] CloneWithBlockCopy(T[] source)
    {
        int length = source.Length;
        T[] destination = new T[length];
        if (length > 0)
            Buffer.BlockCopy(source, 0, destination, 0, length * BlittableHelper<T>.Size);
        return destination;
    }
}

internal static class FastClonerGenerator
{
    private static readonly Type DictionaryInterfaceDefinition = typeof(IDictionary<, >);
    private static readonly Type EnumerableInterfaceDefinition = typeof(IEnumerable<>);
    private struct TypeCloneDispatchCache
    {
        private Type? typeA;
        private FastClonerCache.TypeCloneMetadata? metadataA;
        private Func<object, FastCloneState, object>? recursiveA;
        private Type? typeB;
        private FastClonerCache.TypeCloneMetadata? metadataB;
        private Func<object, FastCloneState, object>? recursiveB;
        private Type? typeC;
        private FastClonerCache.TypeCloneMetadata? metadataC;
        private Func<object, FastCloneState, object>? recursiveC;
        private Type? typeD;
        private FastClonerCache.TypeCloneMetadata? metadataD;
        private Func<object, FastCloneState, object>? recursiveD;
        public void Resolve(Type runtimeType, FastCloneState state, out FastClonerCache.TypeCloneMetadata metadata, out Func<object, FastCloneState, object>? recursiveCloner)
        {
            if (runtimeType == typeA && metadataA is not null)
            {
                metadata = metadataA;
                recursiveCloner = recursiveA;
                return;
            }

            if (runtimeType == typeB && metadataB is not null)
            {
                metadata = metadataB;
                recursiveCloner = recursiveB;
                PromoteSecondToFirst();
                return;
            }

            if (runtimeType == typeC && metadataC is not null)
            {
                metadata = metadataC;
                recursiveCloner = recursiveC;
                PromoteThirdToFirst();
                return;
            }

            if (runtimeType == typeD && metadataD is not null)
            {
                metadata = metadataD;
                recursiveCloner = recursiveD;
                PromoteFourthToFirst();
                return;
            }

            metadata = GetTypeMetadata(runtimeType, state);
            recursiveCloner = metadata.RecursiveCloner;
            typeD = typeC;
            metadataD = metadataC;
            recursiveD = recursiveC;
            typeC = typeB;
            metadataC = metadataB;
            recursiveC = recursiveB;
            typeB = typeA;
            metadataB = metadataA;
            recursiveB = recursiveA;
            typeA = runtimeType;
            metadataA = metadata;
            recursiveA = recursiveCloner;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [SuppressMessage("ReSharper", "SwapViaDeconstruction")] // not compatible with the old tfms, not worth the effort
        private void PromoteSecondToFirst()
        {
            Type? previousTypeA = typeA;
            typeA = typeB;
            typeB = previousTypeA;
            FastClonerCache.TypeCloneMetadata? previousMetadataA = metadataA;
            metadataA = metadataB;
            metadataB = previousMetadataA;
            Func<object, FastCloneState, object>? previousRecursiveA = recursiveA;
            recursiveA = recursiveB;
            recursiveB = previousRecursiveA;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [SuppressMessage("ReSharper", "SwapViaDeconstruction")]
        private void PromoteThirdToFirst()
        {
            Type? previousTypeA = typeA;
            Type? previousTypeB = typeB;
            typeA = typeC;
            typeB = previousTypeA;
            typeC = previousTypeB;
            FastClonerCache.TypeCloneMetadata? previousMetadataA = metadataA;
            FastClonerCache.TypeCloneMetadata? previousMetadataB = metadataB;
            metadataA = metadataC;
            metadataB = previousMetadataA;
            metadataC = previousMetadataB;
            Func<object, FastCloneState, object>? previousRecursiveA = recursiveA;
            Func<object, FastCloneState, object>? previousRecursiveB = recursiveB;
            recursiveA = recursiveC;
            recursiveB = previousRecursiveA;
            recursiveC = previousRecursiveB;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [SuppressMessage("ReSharper", "SwapViaDeconstruction")]
        private void PromoteFourthToFirst()
        {
            Type? previousTypeA = typeA;
            Type? previousTypeB = typeB;
            Type? previousTypeC = typeC;
            typeA = typeD;
            typeB = previousTypeA;
            typeC = previousTypeB;
            typeD = previousTypeC;
            FastClonerCache.TypeCloneMetadata? previousMetadataA = metadataA;
            FastClonerCache.TypeCloneMetadata? previousMetadataB = metadataB;
            FastClonerCache.TypeCloneMetadata? previousMetadataC = metadataC;
            metadataA = metadataD;
            metadataB = previousMetadataA;
            metadataC = previousMetadataB;
            metadataD = previousMetadataC;
            Func<object, FastCloneState, object>? previousRecursiveA = recursiveA;
            Func<object, FastCloneState, object>? previousRecursiveB = recursiveB;
            Func<object, FastCloneState, object>? previousRecursiveC = recursiveC;
            recursiveA = recursiveD;
            recursiveB = previousRecursiveA;
            recursiveC = previousRecursiveB;
            recursiveD = previousRecursiveC;
        }
    }

    internal static FastClonerCache.TypeCloneMetadata GetTypeMetadata(Type type) => FastClonerCache.GetOrAddTypeMetadata(type, BuildTypeMetadata);
    private static FastClonerCache.TypeCloneMetadata GetTypeMetadata(Type type, FastCloneState state)
    {
        if (state.TryGetCachedTypeMetadata(type, out FastClonerCache.TypeCloneMetadata cached))
            return cached;
        FastClonerCache.TypeCloneMetadata metadata = FastClonerCache.GetOrAddTypeMetadata(type, BuildTypeMetadata);
        state.CacheTypeMetadata(type, metadata);
        return metadata;
    }

    private static FastClonerCache.TypeCloneMetadata BuildTypeMetadata(Type type)
    {
        FastClonerCache.TypeShape typeShape = FastClonerExprGenerator.GetTypeShape(type);
        bool isSafe = FastClonerSafeTypes.CanReturnSameObject(type) && (!type.IsValueType || type.IsPrimitive || type.IsEnum);
        bool canHaveCycles = !type.IsValueType && FastClonerCache.GetOrAddCanHaveCycles(type, CalculateCanHaveCycles);
        bool canSkipReferenceTracking = type.IsValueType && !ValueTypeContainsReferenceFieldsCached(type);
        bool hasDirectSelfReference = canHaveCycles && typeShape.HasDirectSelfReference;
        bool hasBehaviorSensitiveMembers = !FastCloner.DisableOptionalFeatures && typeShape.ContainsIgnoredMembers;
        bool requiresSpecializedCloner = type.IsArray || FastClonerExprGenerator.IsDictionaryType(type) || FastClonerExprGenerator.IsSetType(type) || FastClonerExprGenerator.IsListType(type);
        Func<object, FastCloneState, object>? recursive = isSafe ? null : (Func<object, FastCloneState, object>? )FastClonerCache.GetOrAddClass(type, t => GenerateClonerRecursive(t, canSkipReferenceTracking));
        FastClonerCache.CyclePolicy cyclePolicy = !canHaveCycles ? FastClonerCache.CyclePolicy.None : hasDirectSelfReference ? FastClonerCache.CyclePolicy.Worklist : FastClonerCache.CyclePolicy.TrackReferences;
        return new FastClonerCache.TypeCloneMetadata
        {
            IsSafe = isSafe,
            CanSkipReferenceTracking = canSkipReferenceTracking,
            HasBehaviorSensitiveMembers = hasBehaviorSensitiveMembers,
            RequiresSpecializedCloner = requiresSpecializedCloner,
            CyclePolicy = cyclePolicy,
            RecursiveCloner = recursive
        };
    }

    public static T? CloneObject<T>(T? obj)
    {
        if (obj is null)
        {
            return default;
        }

        Type concreteTypeOfObj = obj.GetType();
        Type typeOfT = typeof(T);
        bool hasOptionalTypeOverrides = FastClonerCache.HasActiveTypeBehaviorOverrides;
        if (!typeOfT.IsValueType && concreteTypeOfObj == typeOfT && !hasOptionalTypeOverrides)
        {
            if (TryCloneSafeArrayRoot(obj, concreteTypeOfObj, out T? safeArrayClone))
                return safeArrayClone;
            ClonerCache<T>.CacheEntry cacheEntry = ClonerCache<T>.GetCurrent();
            if (cacheEntry.IsSafe)
            {
                return obj;
            }

            if (cacheEntry.Cloner is not null)
            {
                return cacheEntry.CanUseNoTrackingState ? cacheEntry.Cloner(obj, FastCloneState.GetSimpleState()) : CloneRootWithTrackedState(obj, cacheEntry.Cloner, cacheEntry.Metadata!);
            }
        }

        if (hasOptionalTypeOverrides)
        {
            CloneBehavior? behavior = FastClonerCache.GetTypeBehavior(concreteTypeOfObj);
            switch (behavior)
            {
                case CloneBehavior.Ignore:
                    return default;
                case CloneBehavior.Reference:
                    return obj;
                case CloneBehavior.Shallow:
                    return ShallowClonerGenerator.CloneObject(obj);
            }
        }

        if (FastClonerSafeTypes.DefaultKnownTypes.TryGetValue(concreteTypeOfObj, out _))
        {
            return obj;
        }

        switch (obj)
        {
            case ValueType:
            {
                if (typeOfT == concreteTypeOfObj)
                {
                    bool hasIgnoredMembers = FastClonerExprGenerator.GetTypeShape(concreteTypeOfObj).ContainsIgnoredMembers;
                    if (hasIgnoredMembers || !FastClonerSafeTypes.CanReturnSameObject(concreteTypeOfObj))
                    {
                        FastCloneState structState = FastCloneState.Rent();
                        try
                        {
                            return CloneStructInternal(obj, structState);
                        }
                        finally
                        {
                            FastCloneState.Return(structState);
                        }
                    }

                    return obj;
                }

                break;
            }
        }

        if (!typeOfT.IsValueType && concreteTypeOfObj != typeOfT)
            return (T? )ClonePolymorphic(obj, concreteTypeOfObj);
        return (T? )CloneClassRoot(obj, concreteTypeOfObj);
    }

    private static bool TryCloneSafeArrayRoot<T>(T obj, Type runtimeType, out T? cloned)
    {
        cloned = default;
        if (!runtimeType.IsArray || runtimeType.GetArrayRank() != 1)
            return false;
        Type? elementType = runtimeType.GetElementType();
        if (elementType is null || !FastClonerSafeTypes.CanReturnSameObject(elementType))
            return false;
        Array array = (Array)(object)obj!;
        cloned = (T)array.Clone();
        return true;
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static object? ClonePolymorphic(object obj, Type runtimeType)
    {
        if (!runtimeType.IsValueType && FastClonerSafeTypes.CanReturnSameObject(runtimeType) || runtimeType.IsPrimitive || runtimeType.IsEnum)
            return obj;
        if (obj is Delegate del)
        {
            Type? targetType = del.Target?.GetType();
            if (targetType is not null && FastClonerCache.GetOrAddCompilerGeneratedType(targetType, t => t.GetCustomAttribute<CompilerGeneratedAttribute>()is not null))
                return CloneClassRoot(obj, runtimeType);
            return obj;
        }

        return CloneClassRoot(obj, runtimeType);
    }

    private static object? CloneClassRoot(object obj, Type rootType)
    {
        FastClonerCache.TypeCloneMetadata metadata = GetTypeMetadata(rootType);
        Func<object, FastCloneState, object>? cloner = metadata.RecursiveCloner;
        if (cloner is null)
        {
            return obj;
        }

        if (metadata.CanSkipReferenceTracking || (metadata is { CyclePolicy: FastClonerCache.CyclePolicy.None, HasBehaviorSensitiveMembers: false } && !rootType.IsValueType))
            return cloner(obj, FastCloneState.GetSimpleState());
        return CloneRootWithTrackedState(obj, cloner, metadata);
    }

    private static T CloneRootWithTrackedState<T>(T obj, Func<T, FastCloneState, T> cloner, FastClonerCache.TypeCloneMetadata metadata)
    {
        FastCloneState state = FastCloneState.Rent();
        state.UseWorkList = metadata.CyclePolicy == FastClonerCache.CyclePolicy.Worklist;
        try
        {
            T result;
            if (!state.UseWorkList)
            {
                int current = state.IncrementDepth();
                if (current >= FastCloner.MaxRecursionDepth)
                {
                    state.DecrementDepth();
                    state.UseWorkList = true;
                    result = cloner(obj, state);
                }
                else
                {
                    result = cloner(obj, state);
                    state.DecrementDepth();
                    // if UseWorkList was set during recursive cloning, process the worklist
                    if (!state.UseWorkList)
                    {
                        return result;
                    }
                }
            }
            else
            {
                result = cloner(obj, state);
            }

            Type? lastWorkType = null;
            Func<object, object, FastCloneState, object>? lastClonerTo = null;
            while (state.TryPop(out object from, out object to, out Type type))
            {
                // boxed value types - MemberwiseClone already created a value copy.
                if (type.IsValueType())
                {
                    continue;
                }

                Func<object, object, FastCloneState, object> clonerTo;
                if (type == lastWorkType && lastClonerTo is not null)
                {
                    clonerTo = lastClonerTo;
                }
                else
                {
                    clonerTo = (Func<object, object, FastCloneState, object>)FastClonerCache.GetOrAddDeepClassTo(type, t => ClonerToExprGenerator.GenerateClonerInternal(t, true));
                    lastWorkType = type;
                    lastClonerTo = clonerTo;
                }

                clonerTo(from, to, state);
            }

            return result;
        }
        finally
        {
            FastCloneState.Return(state);
        }
    }

    private static bool CalculateCanHaveCycles(Type type)
    {
        if (type.IsValueType || FastClonerSafeTypes.CanReturnSameObject(type))
            return false;
        if (type.IsArray)
        {
            Type? elementType = type.GetElementType();
            if (elementType is null)
                return true;
            if (FastClonerSafeTypes.CanReturnSameObject(elementType))
                return false;
            if (elementType.IsValueType && !ValueTypeContainsReferenceFields(elementType, []))
                return false;
            return true;
        }

        Type? payloadType = GetCollectionPayloadType(type);
        if (payloadType is not null)
        {
            if (FastClonerSafeTypes.CanReturnSameObject(payloadType))
                return false;
            if (payloadType.IsValueType && !ValueTypeContainsReferenceFieldsCached(payloadType))
                return false;
        }

        Type[] fieldTypes = GetCycleFieldTypes(type);
        for (int i = 0; i < fieldTypes.Length; i++)
        {
            Type fieldType = fieldTypes[i];
            if (FastClonerSafeTypes.CanReturnSameObject(fieldType))
                continue;
            if (!fieldType.IsValueType)
                return true;
            if (ValueTypeContainsReferenceFieldsCached(fieldType))
                return true;
        }

        return false;
    }

    private static bool ValueTypeContainsReferenceFields(Type valueType, HashSet<Type> visited)
    {
        if (!valueType.IsValueType || FastClonerSafeTypes.CanReturnSameObject(valueType))
            return false;
        if (!visited.Add(valueType))
            return true;
        try
        {
            Type[] fieldTypes = GetCycleFieldTypes(valueType);
            for (int i = 0; i < fieldTypes.Length; i++)
            {
                Type fieldType = fieldTypes[i];
                if (FastClonerSafeTypes.CanReturnSameObject(fieldType))
                    continue;
                if (!fieldType.IsValueType)
                    return true;
                if (ValueTypeContainsReferenceFields(fieldType, visited))
                    return true;
            }

            return false;
        }
        finally
        {
            visited.Remove(valueType);
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static bool ValueTypeContainsReferenceFieldsCached(Type valueType)
    {
        return FastClonerCache.GetOrAddValueTypeContainsReferences(valueType, static t => ValueTypeContainsReferenceFields(t, []));
    }

    private static Type[] GetCycleFieldTypes(Type type)
    {
        return FastClonerExprGenerator.GetTypeShape(type).CycleFieldTypes;
    }

    private static Type? GetCollectionPayloadType(Type type)
    {
        return FastClonerCache.GetOrAddCollectionPayloadType(type, ResolveCollectionPayloadType);
    }

    private static Type? ResolveCollectionPayloadType(Type type)
    {
        if (TryGetGenericInterfaceArgument(type, DictionaryInterfaceDefinition, 1, out Type? dictionaryValueType))
            return dictionaryValueType;
        if (TryGetGenericInterfaceArgument(type, EnumerableInterfaceDefinition, 0, out Type? enumerableElementType))
            return enumerableElementType;
        return null;
    }

    private static bool TryGetGenericInterfaceArgument(Type type, Type genericInterfaceDefinition, int argIndex, [NotNullWhen(true)] out Type? argument)
    {
        if (type.IsGenericType && type.GetGenericTypeDefinition() == genericInterfaceDefinition)
        {
            Type[] args = type.GetGenericArguments();
            if ((uint)argIndex < (uint)args.Length)
            {
                argument = args[argIndex];
                return true;
            }
        }

        Type[] interfaces = type.GetInterfaces();
        for (int i = 0; i < interfaces.Length; i++)
        {
            Type current = interfaces[i];
            if (!current.IsGenericType || current.GetGenericTypeDefinition() != genericInterfaceDefinition)
                continue;
            Type[] args = current.GetGenericArguments();
            if ((uint)argIndex < (uint)args.Length)
            {
                argument = args[argIndex];
                return true;
            }
        }

        argument = null;
        return false;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static bool HasActiveTypeBehaviorOverrides(FastCloneState state) => FastClonerCache.HasActiveTypeBehaviorOverrides;
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static bool HasSafeTypeOverrides(FastCloneState state) => FastClonerCache.HasSafeTypeOverrides;
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static CloneBehavior? GetTypeBehavior(Type type, FastCloneState state) => FastClonerCache.GetTypeBehavior(type);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static bool IsTypeIgnored(Type type, FastCloneState state) => FastClonerCache.IsTypeIgnored(type);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static int GetMaxRecursionDepth(FastCloneState state) => state.MaxRecursionDepth;
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static bool CanReturnSameObject(Type type, FastCloneState state) => FastClonerSafeTypes.CanReturnSameObject(type);
    internal static object? CloneClassInternal(object? obj, FastCloneState state)
    {
        return CloneClassInternalCore(obj, state);
    }

    private static object? CloneClassInternalCore(object? obj, FastCloneState state)
    {
        if (obj is null)
            return null;
        Type runtimeType = obj.GetType();
        FastClonerCache.TypeCloneMetadata metadata = GetTypeMetadata(runtimeType, state);
        if (!HasActiveTypeBehaviorOverrides(state) && metadata.IsSafe)
            return obj;
        return CloneClassInternalTyped(obj, runtimeType, state, metadata);
    }

    internal static object? CloneClassInternalNoTracking(object? obj, FastCloneState state)
    {
        return CloneClassInternalNoTrackingCore(obj, state);
    }

    private static object? CloneClassInternalNoTrackingCore(object? obj, FastCloneState state)
    {
        if (obj is null)
            return null;
        Type objType = obj.GetType();
        FastClonerCache.TypeCloneMetadata metadata = GetTypeMetadata(objType, state);
        if (metadata.IsSafe)
            return obj;
        Func<object, FastCloneState, object>? recursiveCloner = metadata.RecursiveCloner;
        return recursiveCloner is null ? obj : recursiveCloner(obj, state);
    }

    internal static object? CloneClassInternalTyped(object obj, Type objType, FastCloneState state)
    {
        return CloneClassInternalTypedCore(obj, objType, state);
    }

    private static object? CloneClassInternalTypedCore(object obj, Type objType, FastCloneState state)
    {
        FastClonerCache.TypeCloneMetadata metadata = GetTypeMetadata(objType, state);
        return CloneClassInternalTyped(obj, objType, state, metadata);
    }

    private static object? CloneClassInternalTyped(object obj, Type objType, FastCloneState state, FastClonerCache.TypeCloneMetadata metadata)
    {
        return CloneClassInternalResolved(obj, state, objType, metadata, metadata.RecursiveCloner);
    }

    private static object? CloneClassInternalResolved(object obj, FastCloneState state, Type objType, FastClonerCache.TypeCloneMetadata metadata, Func<object, FastCloneState, object>? recursiveCloner)
    {
        if (TryGetNonCloningResult(obj, objType, metadata, recursiveCloner, state, out object? nonCloningResult))
        {
            return nonCloningResult;
        }

        object? knownRef = state.GetKnownRef(obj);
        if (knownRef is not null)
            return knownRef;
        if (state.UseWorkList)
        {
            // value types: avoid the worklist because ClonerToExprGenerator.GenerateClonerInternal doesn't support value types
            if (objType.IsValueType())
            {
                object cloned = recursiveCloner(obj, state);
                state.AddKnownRef(obj, cloned);
                return cloned;
            }

            return CloneClassShallowAndTrack(obj, state);
        }

        bool depthIncremented = false;
        try
        {
            depthIncremented = true;
            int current = state.IncrementDepth();
            if (current >= GetMaxRecursionDepth(state))
            {
                state.DecrementDepth();
                depthIncremented = false;
                state.UseWorkList = true;
                // value types: avoid the worklist because ClonerToExprGenerator.GenerateClonerInternal doesn't support value types
                if (objType.IsValueType())
                {
                    object cloned = recursiveCloner(obj, state);
                    state.AddKnownRef(obj, cloned);
                    return cloned;
                }

                return CloneClassShallowAndTrack(obj, state);
            }

            return recursiveCloner(obj, state);
        }
        finally
        {
            if (depthIncremented)
                state.DecrementDepth();
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static bool TryGetNonCloningResult(object obj, Type objType, FastClonerCache.TypeCloneMetadata metadata, Func<object, FastCloneState, object>? recursiveCloner, FastCloneState state, out object? result)
    {
        if (!HasActiveTypeBehaviorOverrides(state))
        {
            if (metadata.IsSafe || recursiveCloner is null)
            {
                result = obj;
                return true;
            }
        }
        else
        {
            if (!HasSafeTypeOverrides(state))
            {
                if (FastClonerSafeTypes.DefaultKnownTypes.ContainsKey(objType))
                {
                    result = obj;
                    return true;
                }

                if (IsTypeIgnored(objType, state))
                {
                    result = null;
                    return true;
                }
            }
            else
            {
                if (IsTypeIgnored(objType, state))
                {
                    result = null;
                    return true;
                }

                if (FastClonerSafeTypes.DefaultKnownTypes.ContainsKey(objType))
                {
                    result = obj;
                    return true;
                }
            }

            if (recursiveCloner is null)
            {
                result = obj;
                return true;
            }
        }

        result = null;
        return false;
    }

    internal static object? CloneClassShallowAndTrack(object? obj, FastCloneState state)
    {
        return CloneClassShallowAndTrackCore(obj, state);
    }

    private static object? CloneClassShallowAndTrackCore(object? obj, FastCloneState state)
    {
        if (obj is null)
        {
            return null;
        }

        Type objType = obj.GetType();
        if (HasActiveTypeBehaviorOverrides(state) && IsTypeIgnored(objType, state))
        {
            return null;
        }

        // boxed structs can be mutated and must be deep-cloned
        if (CanReturnSameObject(objType, state) && !objType.IsValueType())
        {
            return obj;
        }

        object? knownRef = state.GetKnownRef(obj);
        if (knownRef is not null)
        {
            return knownRef;
        }

        FastClonerCache.TypeCloneMetadata metadata = GetTypeMetadata(objType, state);
        // internal structure of dictionaries, etc. needs to be rebuilt
        if (metadata.RequiresSpecializedCloner)
        {
            Func<object, FastCloneState, object>? specialCloner = metadata.RecursiveCloner;
            if (specialCloner is not null)
            {
                return specialCloner(obj, state);
            }
        }

        object shallow = ShallowObjectCloner.CloneObject(obj);
        state.AddKnownRef(obj, shallow);
        if (state.UseWorkList)
        {
            state.EnqueueProcess(obj, shallow, objType);
        }

        return shallow;
    }

    internal static T CloneStructInternal<T>(T obj, FastCloneState state)
    {
        Type typeT = typeof(T);
        Type? underlyingTypeT = Nullable.GetUnderlyingType(typeT);
        // Check for custom type behaviors
        CloneBehavior? behavior = null;
        if (HasActiveTypeBehaviorOverrides(state))
        {
            behavior = GetTypeBehavior(typeT, state);
            if (behavior is null && underlyingTypeT is not null)
                behavior = GetTypeBehavior(underlyingTypeT, state);
        }

        switch (behavior)
        {
            case CloneBehavior.Ignore:
                return default !;
            case CloneBehavior.Reference:
            case CloneBehavior.Shallow:
                return obj;
            default:
            {
                // no loops, no nulls, no inheritance
                Func<T, FastCloneState, T>? cloner = GetClonerForValueType<T>();
                // safe object
                return cloner is null ? obj : cloner(obj, state);
            }
        }
    }

    // when we can't use code generation, we can use these methods
    internal static T[] Clone1DimArraySafeInternal<T>(T[] obj, FastCloneState state)
    {
        T[] outArray = FastArrayCopy<T>.Clone(obj);
        if (state.TrackReferences)
        {
            state.EnsureKnownRefCapacity(outArray.Length + 1);
            state.AddKnownRef(obj, outArray);
        }

        return outArray;
    }

    internal static T[]? Clone1DimArrayStructInternal<T>(T[]? obj, FastCloneState state)
    {
        // not null from called method, but will check it anyway
        if (obj == null)
            return null;
        int l = obj.Length;
        Func<T, FastCloneState, T>? cloner = GetClonerForValueType<T>();
        if (cloner is null)
        {
            T[] clonedArray = FastArrayCopy<T>.Clone(obj);
            if (state.TrackReferences)
            {
                state.EnsureKnownRefCapacity(l + 1);
                state.AddKnownRef(obj, clonedArray);
            }

            return clonedArray;
        }

        T[] outArray = new T[l];
        if (state.TrackReferences)
        {
            state.EnsureKnownRefCapacity(l + 1);
            state.AddKnownRef(obj, outArray);
        }

        for (int i = 0; i < l; i++)
            outArray[i] = cloner(obj[i], state);
        return outArray;
    }

    internal static T[]? Clone1DimArrayClassInternal<T>(T[]? obj, FastCloneState state)
    {
        // not null from called method, but will check it anyway
        if (obj == null)
            return null;
        int l = obj.Length;
        T[] outArray = new T[l];
        state.EnsureKnownRefCapacity(l + 1);
        if (state.UseWorkList)
            state.EnsureWorkQueueCapacity(l);
        state.AddKnownRef(obj, outArray);
        Type declaredType = typeof(T);
        if (!declaredType.IsValueType && CanReturnSameObject(declaredType, state) && !HasActiveTypeBehaviorOverrides(state))
        {
            Array.Copy(obj, outArray, l);
            return outArray;
        }

        bool hasOptionalTypeOverrides = HasActiveTypeBehaviorOverrides(state);
        TypeCloneDispatchCache dispatch = default;
        Type? lastType = null;
        FastClonerCache.TypeCloneMetadata? lastMetadata = null;
        Func<object, FastCloneState, object>? lastRecursiveCloner = null;
        for (int i = 0; i < l; i++)
        {
            T? item = obj[i];
            if (item is null)
            {
                outArray[i] = item;
                continue;
            }

            Type runtimeType = item.GetType();
            if (!hasOptionalTypeOverrides && ((!runtimeType.IsValueType && CanReturnSameObject(runtimeType, state)) || runtimeType.IsPrimitive || runtimeType.IsEnum))
            {
                outArray[i] = item;
                continue;
            }

            FastClonerCache.TypeCloneMetadata metadata;
            Func<object, FastCloneState, object>? recursiveCloner;
            if (runtimeType == lastType && lastMetadata is not null)
            {
                metadata = lastMetadata;
                recursiveCloner = lastRecursiveCloner;
            }
            else
            {
                dispatch.Resolve(runtimeType, state, out metadata, out recursiveCloner);
                lastType = runtimeType;
                lastMetadata = metadata;
                lastRecursiveCloner = recursiveCloner;
            }

            outArray[i] = (T)CloneClassInternalResolved(item, state, runtimeType, metadata, recursiveCloner)!;
        }

        return outArray;
    }

    internal static List<T>? CloneListSafeInternal<T>(List<T>? obj, FastCloneState state)
    {
        if (obj is null)
            return null;
        int count = obj.Count;
        List<T> result = new List<T>(count);
        state.AddKnownRef(obj, result);
        CollectionsMarshal.SetCount(result, count);
        ReadOnlySpan<T> srcSpan = CollectionsMarshal.AsSpan(obj);
        Span<T> destSpan = CollectionsMarshal.AsSpan(result);
        srcSpan.CopyTo(destSpan);
        return result;
    }

    internal static List<T>? CloneListStructInternal<T>(List<T>? obj, FastCloneState state)
        where T : struct
    {
        if (obj is null)
            return null;
        int count = obj.Count;
        List<T> result = new List<T>(count);
        state.AddKnownRef(obj, result);
        Func<T, FastCloneState, T>? cloner = GetClonerForValueType<T>();
        if (cloner is null)
        {
            CollectionsMarshal.SetCount(result, count);
            ReadOnlySpan<T> srcSpan = CollectionsMarshal.AsSpan(obj);
            Span<T> destSpan = CollectionsMarshal.AsSpan(result);
            srcSpan.CopyTo(destSpan);
            return result;
        }

        CollectionsMarshal.SetCount(result, count);
        Span<T> span = CollectionsMarshal.AsSpan(result);
        for (int i = 0; i < count; i++)
            span[i] = cloner(obj[i], state);
        return result;
    }

    internal static List<T?>? CloneListClassInternal<T>(List<T?>? obj, FastCloneState state)
        where T : class
    {
        if (obj is null)
            return null;
        int count = obj.Count;
        state.EnsureKnownRefCapacity(count + 1);
        if (state.UseWorkList)
            state.EnsureWorkQueueCapacity(count);
        List<T?> result = new List<T?>(count);
        state.AddKnownRef(obj, result);
        Type declaredType = typeof(T);
        CollectionsMarshal.SetCount(result, count);
        ReadOnlySpan<T?> srcSpan = CollectionsMarshal.AsSpan(obj);
        Span<T?> span = CollectionsMarshal.AsSpan(result);
        if (declaredType.IsSealed)
        {
            FastClonerCache.TypeCloneMetadata metadata = GetTypeMetadata(declaredType, state);
            Func<object, FastCloneState, object>? recursiveCloner = metadata.RecursiveCloner;
            for (int i = 0; i < count; i++)
            {
                T? item = srcSpan[i];
                span[i] = item is null ? null : (T? )CloneClassInternalResolved(item, state, declaredType, metadata, recursiveCloner);
            }

            return result;
        }

        TypeCloneDispatchCache dispatch = default;
        Type? lastType = null;
        FastClonerCache.TypeCloneMetadata? lastMetadata = null;
        Func<object, FastCloneState, object>? lastRecursiveCloner = null;
        for (int i = 0; i < count; i++)
        {
            T? item = srcSpan[i];
            if (item is null)
            {
                span[i] = null;
                continue;
            }

            Type runtimeType = item.GetType();
            FastClonerCache.TypeCloneMetadata metadata;
            Func<object, FastCloneState, object>? recursiveCloner;
            if (runtimeType == lastType && lastMetadata is not null)
            {
                metadata = lastMetadata;
                recursiveCloner = lastRecursiveCloner;
            }
            else
            {
                dispatch.Resolve(runtimeType, state, out metadata, out recursiveCloner);
                lastType = runtimeType;
                lastMetadata = metadata;
                lastRecursiveCloner = recursiveCloner;
            }

            span[i] = (T? )CloneClassInternalResolved(item, state, runtimeType, metadata, recursiveCloner);
        }

        return result;
    }

    internal static Dictionary<TKey, TValue>? CloneDictionarySafeInternal<TKey, TValue>(Dictionary<TKey, TValue>? obj, FastCloneState state)
        where TKey : notnull
    {
        if (obj is null)
            return null;
        Dictionary<TKey, TValue> result = new Dictionary<TKey, TValue>(obj.Count, obj.Comparer);
        state.AddKnownRef(obj, result);
        bool ignoreValues = HasActiveTypeBehaviorOverrides(state) && IsTypeIgnored(typeof(TValue), state);
        foreach (KeyValuePair<TKey, TValue> kvp in obj)
        {
            ref TValue valueRef = ref CollectionsMarshal.GetValueRefOrAddDefault(result, kvp.Key, out _);
            valueRef = ignoreValues ? default ! : kvp.Value;
        }

        return result;
    }

    internal static Dictionary<TKey, TValue>? CloneDictionaryStructValueInternal<TKey, TValue>(Dictionary<TKey, TValue>? obj, FastCloneState state)
        where TKey : notnull where TValue : struct
    {
        if (obj is null)
            return null;
        Dictionary<TKey, TValue> result = new Dictionary<TKey, TValue>(obj.Count, obj.Comparer);
        state.AddKnownRef(obj, result);
        bool ignoreValues = HasActiveTypeBehaviorOverrides(state) && IsTypeIgnored(typeof(TValue), state);
        if (ignoreValues)
        {
            foreach (KeyValuePair<TKey, TValue> kvp in obj)
            {
                ref TValue valueRef = ref CollectionsMarshal.GetValueRefOrAddDefault(result, kvp.Key, out _);
                valueRef = default;
            }

            return result;
        }

        Func<TValue, FastCloneState, TValue>? cloner = GetClonerForValueType<TValue>();
        if (cloner is null)
        {
            foreach (KeyValuePair<TKey, TValue> kvp in obj)
            {
                ref TValue valueRef = ref CollectionsMarshal.GetValueRefOrAddDefault(result, kvp.Key, out _);
                valueRef = kvp.Value;
            }
        }
        else
        {
            foreach (KeyValuePair<TKey, TValue> kvp in obj)
            {
                ref TValue valueRef = ref CollectionsMarshal.GetValueRefOrAddDefault(result, kvp.Key, out _);
                valueRef = cloner(kvp.Value, state);
            }
        }

        return result;
    }

    internal static Dictionary<TKey, TValue?>? CloneDictionaryClassValueInternal<TKey, TValue>(Dictionary<TKey, TValue?>? obj, FastCloneState state)
        where TKey : notnull where TValue : class
    {
        if (obj is null)
            return null;
        state.EnsureKnownRefCapacity(obj.Count + 1);
        Type declaredType = typeof(TValue);
        bool ignoreDeclaredValues = HasActiveTypeBehaviorOverrides(state) && IsTypeIgnored(declaredType, state);
        if (declaredType == typeof(object))
            return (Dictionary<TKey, TValue?>? )(object? )CloneDictionaryObjectValueInternal((Dictionary<TKey, object?>)(object)obj, state);
        Dictionary<TKey, TValue?> result = new Dictionary<TKey, TValue?>(obj.Count, obj.Comparer);
        state.AddKnownRef(obj, result);
        if (declaredType.IsSealed)
        {
            FastClonerCache.TypeCloneMetadata? metadata = ignoreDeclaredValues ? null : GetTypeMetadata(declaredType, state);
            Func<object, FastCloneState, object>? recursiveCloner = metadata?.RecursiveCloner;
            foreach (KeyValuePair<TKey, TValue?> kvp in obj)
            {
                TValue? cloned;
                if (kvp.Value is null || ignoreDeclaredValues)
                {
                    cloned = null;
                }
                else
                {
                    cloned = (TValue? )CloneClassInternalResolved(kvp.Value, state, declaredType, metadata!, recursiveCloner);
                }

                ref TValue? valueRef = ref CollectionsMarshal.GetValueRefOrAddDefault(result, kvp.Key, out _);
                valueRef = cloned;
            }

            return result;
        }

        Type? lastType = null;
        FastClonerCache.TypeCloneMetadata? lastMetadata = null;
        Func<object, FastCloneState, object>? lastRecursive = null;
        foreach (KeyValuePair<TKey, TValue?> kvp in obj)
        {
            TValue? value = kvp.Value;
            if (value is null)
            {
                ref TValue? nullRef = ref CollectionsMarshal.GetValueRefOrAddDefault(result, kvp.Key, out _);
                nullRef = null;
                continue;
            }

            Type runtimeType = value.GetType();
            if (HasActiveTypeBehaviorOverrides(state) && IsTypeIgnored(runtimeType, state))
            {
                ref TValue? ignoredRef = ref CollectionsMarshal.GetValueRefOrAddDefault(result, kvp.Key, out _);
                ignoredRef = null;
                continue;
            }

            if (CanReturnSameObject(runtimeType, state))
            {
                ref TValue? valueRef = ref CollectionsMarshal.GetValueRefOrAddDefault(result, kvp.Key, out _);
                valueRef = value;
                continue;
            }

            FastClonerCache.TypeCloneMetadata metadata;
            if (runtimeType == lastType && lastMetadata is not null)
            {
                metadata = lastMetadata;
            }
            else
            {
                metadata = lastMetadata = GetTypeMetadata(runtimeType, state);
                lastRecursive = metadata.RecursiveCloner;
                lastType = runtimeType;
            }

            TValue? cloned = (TValue? )CloneClassInternalResolved(value, state, runtimeType, metadata, lastRecursive);
            ref TValue? clonedRef = ref CollectionsMarshal.GetValueRefOrAddDefault(result, kvp.Key, out _);
            clonedRef = cloned;
        }

        return result;
    }

    private static Dictionary<TKey, object?> CloneDictionaryObjectValueInternal<TKey>(Dictionary<TKey, object?> obj, FastCloneState state)
        where TKey : notnull
    {
        Dictionary<TKey, object?> result = new Dictionary<TKey, object?>(obj.Count, obj.Comparer);
        state.AddKnownRef(obj, result);
        TypeCloneDispatchCache dispatch = default;
        Type? lastType = null;
        FastClonerCache.TypeCloneMetadata? lastMetadata = null;
        Func<object, FastCloneState, object>? lastRecursiveCloner = null;
        foreach (KeyValuePair<TKey, object?> kvp in obj)
        {
            object? value = kvp.Value;
            if (value is null)
            {
                ref object? nullRef = ref CollectionsMarshal.GetValueRefOrAddDefault(result, kvp.Key, out _);
                nullRef = null;
                continue;
            }

            Type runtimeType = value.GetType();
            if (CanReturnSameObject(runtimeType, state))
            {
                ref object? safeRef = ref CollectionsMarshal.GetValueRefOrAddDefault(result, kvp.Key, out _);
                safeRef = value;
                continue;
            }

            FastClonerCache.TypeCloneMetadata metadata;
            Func<object, FastCloneState, object>? recursiveCloner;
            if (runtimeType == lastType && lastMetadata is not null)
            {
                metadata = lastMetadata;
                recursiveCloner = lastRecursiveCloner;
            }
            else
            {
                dispatch.Resolve(runtimeType, state, out metadata, out recursiveCloner);
                lastType = runtimeType;
                lastMetadata = metadata;
                lastRecursiveCloner = recursiveCloner;
            }

            object cloned = CloneClassInternalResolved(value, state, runtimeType, metadata, recursiveCloner)!;
            ref object? clonedRef = ref CollectionsMarshal.GetValueRefOrAddDefault(result, kvp.Key, out _);
            clonedRef = cloned;
        }

        return result;
    }

    // relatively frequent case. specially handled
    internal static T[, ]? Clone2DimArrayInternal<T>(T[, ]? obj, FastCloneState state)
    {
        // not null from called method, but will check it anyway
        if (obj is null)
        {
            return null;
        }

        // we cannot determine by type multidim arrays (one dimension is possible)
        // so, will check for index here
        int lb1 = obj.GetLowerBound(0);
        int lb2 = obj.GetLowerBound(1);
        if (lb1 != 0 || lb2 != 0)
            return (T[, ])CloneAbstractArrayInternal(obj, state)!;
        int l1 = obj.GetLength(0);
        int l2 = obj.GetLength(1);
        T[, ] outArray = new T[l1, l2];
        state.AddKnownRef(obj, outArray);
        if (CanReturnSameObject(typeof(T), state))
        {
            Array.Copy(obj, outArray, obj.Length);
            return outArray;
        }

        if (typeof(T).IsValueType())
        {
            Func<T, FastCloneState, T>? cloner = GetClonerForValueType<T>();
            if (cloner is null)
            {
                Array.Copy(obj, outArray, obj.Length);
                return outArray;
            }

            for (int i = 0; i < l1; i++)
                for (int k = 0; k < l2; k++)
                    outArray[i, k] = cloner(obj[i, k], state);
        }
        else
        {
            for (int i = 0; i < l1; i++)
                for (int k = 0; k < l2; k++)
                    outArray[i, k] = (T)CloneClassInternal(obj[i, k], state)!;
        }

        return outArray;
    }

    internal static Array? CloneAbstractArrayInternal(Array? obj, FastCloneState state)
    {
        // not null from called method, but will check it anyway
        if (obj == null)
            return null;
        int rank = obj.Rank;
        int[] lengths = new int[rank];
        int[] lowerBounds = new int[rank];
        bool hasZeroLength = false;
        for (int i = 0; i < rank; i++)
        {
            int length = obj.GetLength(i);
            int lowerBound = obj.GetLowerBound(i);
            lengths[i] = length;
            lowerBounds[i] = lowerBound;
            hasZeroLength |= length == 0;
        }

        Type elementType = obj.GetType().GetElementType()!;
        Array outArray = Array.CreateInstance(elementType, lengths, lowerBounds);
        state.AddKnownRef(obj, outArray);
        // we're unable to set any value to this array, so, just return it
        if (hasZeroLength)
            return outArray;
        if (CanReturnSameObject(elementType, state))
        {
            Array.Copy(obj, outArray, obj.Length);
            return outArray;
        }

        switch (rank)
        {
            case 1:
            {
                int lower = lowerBounds[0];
                int upper = lower + lengths[0];
                for (int i = lower; i < upper; i++)
                    outArray.SetValue(CloneClassInternal(obj.GetValue(i), state), i);
                return outArray;
            }

            case 2:
            {
                int lower0 = lowerBounds[0];
                int lower1 = lowerBounds[1];
                int upper0 = lower0 + lengths[0];
                int upper1 = lower1 + lengths[1];
                for (int i = lower0; i < upper0; i++)
                    for (int k = lower1; k < upper1; k++)
                        outArray.SetValue(CloneClassInternal(obj.GetValue(i, k), state), i, k);
                return outArray;
            }
        }

        int[] idxes = new int[rank];
        Array.Copy(lowerBounds, idxes, rank);
        int ofs = rank - 1;
        while (true)
        {
            outArray.SetValue(CloneClassInternal(obj.GetValue(idxes), state), idxes);
            idxes[ofs]++;
            if (idxes[ofs] >= lowerBounds[ofs] + lengths[ofs])
            {
                do
                {
                    if (ofs == 0)
                        return outArray;
                    idxes[ofs] = lowerBounds[ofs];
                    ofs--;
                    idxes[ofs]++;
                }
                while (idxes[ofs] >= lowerBounds[ofs] + lengths[ofs]);
                ofs = rank - 1;
            }
        }
    }

    internal static Func<T, FastCloneState, T>? GetClonerForValueType<T>() => (Func<T, FastCloneState, T>? )FastClonerCache.GetOrAddStructAsObject(typeof(T), t => GenerateCloner(t, false));
    private static object? GenerateClonerRecursive(Type t, bool skipCycleTracking)
    {
        if (FastClonerSafeTypes.CanReturnSameObject(t) && !t.IsValueType())
            return null;
        return FastClonerExprGenerator.GenerateClonerInternal(t, asObject: true, skipCycleTracking: skipCycleTracking, useShallowClassClone: false);
    }

    private static object? GenerateCloner(Type t, bool asObject)
    {
        if (FastClonerSafeTypes.CanReturnSameObject(t) && asObject && !t.IsValueType())
            return null;
        bool skipCycleTracking = !asObject && t.IsValueType && !ValueTypeContainsReferenceFieldsCached(t);
        return FastClonerExprGenerator.GenerateClonerInternal(t, asObject, skipCycleTracking: skipCycleTracking, useShallowClassClone: false);
    }

    public static object? CloneObjectTo(object? objFrom, object? objTo, bool isDeep)
    {
        if (objTo == null)
            return null;
        if (objFrom == null)
            throw new ArgumentNullException(nameof(objFrom), "Cannot copy null object to another");
        Type type = objFrom.GetType();
        if (!type.IsInstanceOfType(objTo))
            throw new InvalidOperationException("From object should be derived from From object, but From object has type " + objFrom.GetType().FullName + " and to " + objTo.GetType().FullName);
        if (objFrom is string)
            throw new InvalidOperationException("It is forbidden to clone strings");
        Func<object, object, FastCloneState, object>? cloner = (Func<object, object, FastCloneState, object>? )(isDeep ? FastClonerCache.GetOrAddDeepClassTo(type, t => ClonerToExprGenerator.GenerateClonerInternal(t, true)) : FastClonerCache.GetOrAddShallowClassTo(type, t => ClonerToExprGenerator.GenerateClonerInternal(t, false)));
        if (cloner is null)
            return objTo;
        FastCloneState state = FastCloneState.Rent();
        try
        {
            object result = cloner(objFrom, objTo, state);
            if (!isDeep)
            {
                return result;
            }

            Type? lastWorkType = null;
            Func<object, object, FastCloneState, object>? lastClonerTo = null;
            while (state.TryPop(out object from, out object to, out Type workItemType))
            {
                Func<object, object, FastCloneState, object> clonerTo;
                if (workItemType == lastWorkType && lastClonerTo is not null)
                {
                    clonerTo = lastClonerTo;
                }
                else
                {
                    clonerTo = (Func<object, object, FastCloneState, object>)FastClonerCache.GetOrAddDeepClassTo(workItemType, t => ClonerToExprGenerator.GenerateClonerInternal(t, true));
                    lastWorkType = workItemType;
                    lastClonerTo = clonerTo;
                }

                clonerTo(from, to, state);
            }

            return result;
        }
        finally
        {
            FastCloneState.Return(state);
        }
    }
}
