/* This code was generated by FastCloner.Internalization.Builder, do not edit manually
FastCloner is licensed under the MIT licence. https://github.com/lofcz/FastCloner
*/

using System;

namespace Foundatio.FastCloner.Code;
/// <summary>
/// Marks a member or type for shallow cloning instead of deep cloning.
/// When applied to a type, all usages perform MemberwiseClone without recursing into members.
/// When applied to a member, that reference is copied directly without deep cloning its contents.
/// This is useful for parent references, shared state, or when deep cloning would cause issues.
/// </summary>
/// <example>
/// <code>
/// // Type-level: shallow clone the entire Config type
/// [FastClonerShallow]
/// public class Config { }
/// 
/// // Member-level: shallow clone only this member
/// public class Node
/// {
///     [FastClonerShallow]
///     public ParentObject Parent { get; set; }
/// }
/// </code>
/// </example>
/// <remarks>
/// This attribute is a shorthand for <c>[FastClonerBehavior(CloneBehavior.Shallow)]</c>.
/// </remarks>
[AttributeUsage(AttributeTargets.Field | AttributeTargets.Property | AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Interface)]
internal class FastClonerShallowAttribute : FastClonerBehaviorAttribute
{
    /// <summary>
    /// Initializes a new instance of <see cref = "FastClonerShallowAttribute"/>.
    /// </summary>
    public FastClonerShallowAttribute() : base(CloneBehavior.Shallow)
    {
    }
}
