#nullable enable

/* This code was generated by FastCloner.Internalization.Builder, do not edit manually
FastCloner is licensed under the MIT licence. https://github.com/lofcz/FastCloner
*/

using System;

namespace Foundatio.FastCloner;
/// <summary>
///     Apply this attribute to a struct to indicate it should be treated as a "Safe Handle" or identity-preserving type.
///     When applied, FastCloner will NOT attempt to deep-clone readonly fields on this struct, preventing
///     identity breakage for types that rely on specific internal singleton or handle references.
/// </summary>
[AttributeUsage(AttributeTargets.Struct)]
internal class FastClonerSafeHandleAttribute : Attribute
{
}
