/* This code was generated by FastCloner.Internalization.Builder, do not edit manually
FastCloner is licensed under the MIT licence. https://github.com/lofcz/FastCloner
*/

using System.Runtime.CompilerServices;

namespace Foundatio.FastCloner.Code;
/// <summary>
/// Internal helper class used to perform shallow object cloning
/// </summary>
internal static class ShallowObjectCloner
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static object CloneObject(object obj) => DirectCloneObject(obj);
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "MemberwiseClone")]
    public static extern object DirectCloneObject(object obj);
}
